services:
  mongo:
    image: mongo:7
    container_name: app-attendance-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-app_user_demo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-app_password_demo}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-app_attendance}
    volumes:
      - app_attendance_mongo_data:/data/db
    networks:
      - app_attendance_network

volumes:
  app_attendance_mongo_data:

networks:
  app_attendance_network:
    driver: bridge
